= Описание API по возможностям пользователя

Примечание: если запрос нуждается в авторизации, в заголовках запроса надо добавить *Authorization* со значением
полученного после авторизации токена.

|===
|Запрос | Назначение | isAuthenticated | Response

|`POST /checkUserEmail`
| Проверить уникальность почты
| false
a|
* *200* - значит введенный email не занят
* *409* - значит введенный email уже занят

|`POST /signUp`
| Зарегистрировать пользователя
| false
a|
* *200* - пользователь зарегистрирован

|`POST /login`
|Авторизовать зарегистрированного пользователя
| false
a|
* *200* - возвращается токен
* *400* - значит введенные email или пароль неверны

|`POST /recover`
|Отправить запрос на восстановление пароля пользователя
| false
a|
* *200* - письмо на воостановление пароля отправлено
* *400* - значит нет пользователя с таким email

|`POST /recover/{user-id}`
|Восстановить пароль пользователя *(запрос из письма на восстановление, пока не доделано)*
| false
a|
* *200* - пароль изменен
* *404* - значит нет пользователя с таким id

|`GET /activate/{activation-code}`
|Активировать аккаунт пользователя
| false
a|
* *200* - пользователь активирован
* *404* - значит нет пользователя с таким activation code

|===

== Примеры запросов

=== `POST /checkUserEmail` - регистрация

При вводе пользователем email для регистрации, клиент отправляет *Json*:

    {
        "email": "test@mail.ru"
    }

=== `POST /signUp` - регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "email": "test3@mail.ru",
        "password": "test",
        "surname": "test",
        "name": "Aina"
    }

=== `POST /login` - авторизация

Для авторизации отправляется *Json*:

    {
        "email": "user@mail.ru",
        "password": "user1"
    }

При успешной авторизации в ответе придет объект токена.
Пример ответа в случае успеха:

    {
        "value": "eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVr",
        "status": "VALID"
    }

=== `POST /recover` - восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.