= Описание API по Dogger

== Методы

|===
|Метод | Назначение
|`POST /signUp`
|Создать пользователя

|`POST /login`
|Авторизовать зарегистрированного пользователя

|`GET /profile`
|Получить информацию о пользователе

|`POST /profile`
|Редактировать профиль пользователя

|`POST /addDog`
|Добавить собаку пользователю

|`POST` /recover/{user-id}
|Восстановить пароль пользователя

|`GET` /activate/{activation-code}
|Активировать аккаунт пользователя

|`POST /addMeeting`
|Добавить новое мероприятие

|`GET /meetings`
|Получить список всех мероприятий

|`POST` /delete
|Удалить пользователя из базы данных

|===

=== Регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "login": "user",
        "password": "user1",
        "fullName": "User user user"
    }

=== Авторизация

Для авторизации отправляется *Json*:

    {
        "login": "user",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен.

*Все последующие запросы должны включать в себя значение данного токена.*

=== Профиль

Чтобы перейти на страницу профиля, в заголовках запроса надо добавить *Authorization* со значением полученного токена.

Для редактирования профиля пользователя отправляется *Json*:

    {
        "login": "kama",
        "password": "kama",
        "fullName": "Kamila Nigmetzyanova",
        "dateOfBirth": "1999-03-09"
    }

=== Добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней.
Чтобы добавить питомца, следует отправить *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog.A little bit coward"
    }

При успешном запросе в профиле пользователя появится собака.

=== Восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "login": "test",
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.

=== Добавить мероприятие

Пользователь может добавить новое мероприятие/митинг/ивент.
Чтобы добавить мероприятие, следует отправить *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный
пользователь. В списке всех митингов появится новый.

=== Удалить пользователя

Можно удалить пользователя из базы данных, отправив запрос:

    {
        "login": "test"
    }
