= Описание API по Dogger

== Методы

=== Пользователь

|===
|Метод | Назначение
|`POST /signUp`
|Создать пользователя

|`POST /login`
|Авторизовать зарегистрированного пользователя

|`GET /profile`
|Получить информацию о текущем пользователе

|`GET /profile/{user-id}`
|Получить информацию о другом пользователе

|`POST /profile`
|Редактировать профиль пользователя

|`POST /addDog`
|Добавить собаку пользователю

|`POST` /recover/{user-id}
|Восстановить пароль пользователя

|`GET` /activate/{activation-code}
|Активировать аккаунт пользователя

|`POST` /delete
|Удалить пользователя из базы данных

|===

=== Прогулки

|===
|Метод | Назначение | isAuthenticated | Return type

|`POST /addMeeting`
| Добавить новую прогулку
| true
| новая прогулка

|`POST /editMeeting?meetingId={meeting-id}`
| Редактировать прогулку
| true
| измененная прогулка или 403, если такой прогулки не существует или пользователь не является ее создателем

|`GET /meetings/future`
| Получить список всех прогулок
| false
| массив всех будущих прогулок (мб пустой)

|`GET /meetings/joined?userId={user-id}`
| Получить список всех прогулок, в которых участвует пользователь
| true
| массив прогулок, в которых участвует пользователь (мб пустой)

|`GET /meetings/my`
| Получить список всех прогулок, созданных текущим пользователем
| true
| массив прогулок, созданных пользователем (мб пустой)

|`GET /meetings/{meeting-id}`
| Получить полную информацию о прогулке
| false
| Детальная информация о прогулке или not found

|`POST /meetings/{meeting-id}/join`
| Присоединиться к прогулке
| true
| информация о прогулке если присоединился, 400 если уже участвуешь/нет такой прогулки,
401 если неавторизован

|`POST /meetings/{meeting-id}/unjoin`
| Отсоединиться от прогулки
| true
| информация о прогулке если отсоединился, 400 если не участвуешь/нет такой прогулки,
401 если неавторизован

|===

=== Места (парки, кафе, площадки)

|===
|Метод | Назначение | isAuthenticated | Return type

|`GET /places/all`
| Получить все места
| false
| массив всех мест

|`POST /addPlace`
| Добавить новое место
| true
| информация о новом месте

|`GET /places/{place-id}`
| Получить информацию о месте
| false
| информация о месте

|`POST` /editDogs
|Редактировать питомцев пользователя

|===

=== Регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "email": "user@mail.ru",
        "password": "user1",
        "fullName": "User user user",
        "city": "Kazan",
        "phoneNumber": "89176564663"
    }

=== Авторизация

Для авторизации отправляется *Json*:

    {
        "email": "user@mail.ru",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен.

*Все последующие запросы должны включать в себя значение данного токена.*

=== Профиль

Чтобы перейти на страницу профиля, в заголовках запроса надо добавить *Authorization* со значением полученного токена.

Для редактирования профиля пользователя отправляется *Json*:

    {
        "fullName": "New fullName",
        "dateOfBirth": "2018-04-15T00:00:00.000+0000",
        "city": "Kazan",
        "phoneNumber": "891789099878"
    }

В ответе приходит *Json*:

    {
            "dogs": [
        {
          "id": 4,
          "name": "test",
          "breed": "test",
          "dateOfBirth": "2018-04-15T00:00:00.000+0000",
          "sex": "test",
          "size": "test",
          "photo_path": null,
          "information": "test"
        },
        {
          "id": 5,
          "name": "dog one",
          "breed": "labrador",
          "dateOfBirth": "2018-04-15T00:00:00.000+0000",
          "sex": "male",
          "size": "big",
          "photo_path": null,
          "information": "good"
        }
      ],
      "fullName": "Aina aina aina",
      "dateOfBirth": "1999-02-13T19:00:00.000+0000",
      "meetings": [],
      "email": "user@mail.ru"
    }

Для получения страницы профиля другого пользователя токен отсылать не нужно. Ответ выглядит так:

    {
        "dogs": [],
        "fullName": "Test Test",
        "dateOfBirth": null,
        "meetings": [
            {
                "id": 18,
                "name": "Khakima 49-54",
                "description": "For dog walkers from our district",
                "date": "2020-04-30T17:00:00.000+0000",
                "coordinateX": 65.56348,
                "coordinateY": 63.14327
            }
        ],
        "id": 3,
        "email": "user@mail.ru"
    }

=== Добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней.
Чтобы добавить питомца, следует отправить *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog. Little bit coward"
    }

При успешном запросе в профиле пользователя появится собака.

=== Редактировать информацию о собаке

Пользователь может редактировать информацию своих питомцев. Для этого нужно отправить *Json*:

    [
      {
        "id": 5,
        "name": "tesla",
        "breed": "jack rassel",
        "dateOfBirth": "",
        "information": "good girl"
      },
        {
        ...
        }
    ]

Если никаких изменений не выполнено, то в ответ придет сообщение: No changes in dogs.

=== Восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.

=== Удалить пользователя

Можно удалить пользователя из базы данных, отправив запрос c параметром userId=*id пользователя*.

=== Добавить прогулку

Пользователь может добавить новую прогулку/встречу.
Чтобы добавить мероприятие, следует отправить *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный пользователь
(который автоматически попадает в список участников мероприятия).
В списке всех митингов появится новый. В ответ придет информация о новой добавленной прогулке.

=== Редактировать прогулку

Пользователь может редактировать свою прогулку/встречу.
Следует отправить *Json* (неизмененные поля заполнены старыми данными):

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

Если такой прогулки не существует или пользователь не является ее создателем, вернется ошибка *403 Forbidden*.
Если пользователь неавторизован, вернется ошибка *401 Unauthorized*.
При успешном запросе вернется информация об обновленной прогулке.

=== Получить список всех прогулок

Можно отобразить список всех будущих прогулок в ответ на *GET /meetings/future*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      },
      {
        "id": 7,
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 0
      }
    ]

=== Получить список всех прогулок, в которых участвует пользователь

Можно отобразить список всех прогулок в ответ на *GET /meetings/joined/?userId={user-id}*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      }
    ]

=== Получить список всех прогулок, созданных пользователем

Можно отобразить список всех прогулок в ответ на *GET /meetings/my*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      }
    ]

=== Получить детальную информацию о прогулке

Ответ выглядит следующим образом:

    {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": {
            "id": 1,
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "dateOfBirth": null,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
        },
        "participants": [
            {
                "id": 1,
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": [
                    {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    },
                    {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    }
                ],
            },
            {
                "id": 2,
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": []
            }
        ]
    }

=== Присоединиться к прогулке

После получения запроса проверяется, участвует ли пользователь в выбранной прогулке или еще нет, затем пользователь
добавляется в участники, если не был там.

=== Отсоединиться от прогулки

После получения запроса проверяется, участвует ли пользователь в выбранной прогулке или еще нет, затем пользователь
убирается из участников, если был там. Если это последний участник прогулки (то есть автор прогулки уже тоже
отсоединился от нее), прогулка удаляется.

=== Получить список всех мест

Можно отобразить список всех мест в ответ на *GET /places/all*. Пример ответа:

    {
        "id": 1,
        "name": "test place",
        "photo_path": "test_url",
        "description": "coffee shop",
        "coordinateX": 55.73,
        "coordinateY": 55.76,
        "type": "COFFEE",
        "amenities": [
            "WATER",
            "FOOD"
        ],
        "creator": {
            "id": 1,
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "dateOfBirth": null,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
            "questions": [],
            "answers": [],
            "myMeetings": [
                {
                    "id": 7,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                },
                {
                    "id": 8,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                }
            ]
        }
    }

=== Добавить место

Пользователь может добавить новое заведение/лес/площадку.
Чтобы добавить, следует отправить *Json*:

    {
      "name": "test place",
      "description": "coffee shop",
      "photoPath": "test_url",
      "placeType": "COFFEE",
      "coordinateX": "55.73",
      "coordinateY": "55.76",
      "amenities": [ "WATER", "FOOD"]
    }

При успешном запросе в базе данных появится место, автором которого будет текущий авторизованный пользователь.
В ответ придет информация о новом созданном месте.

=== Получить детальную информацию о месте

Ответ может выглядеть так:

    {
        "id": 1,
        "name": "test place",
        "photo_path": "test_url",
        "description": "coffee shop",
        "coordinateX": 55.73,
        "coordinateY": 55.76,
        "type": "COFFEE",
        "amenities": [
            "WATER",
            "FOOD"
        ],
        "creator": {
            "id": 1,
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "dateOfBirth": null,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
            "questions": [],
            "answers": [],
            "myMeetings": [
                {
                    "id": 7,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                },
                {
                    "id": 8,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                }
            ]
        }
    }
