= Описание API по возможностям пользователя

Примечание: если запрос нуждается в авторизации, в заголовках запроса надо добавить *Authorization* со значением
полученного после авторизации токена.

|===
|Запрос | Назначение | isAuthenticated | Response

|`GET /profile`
|Получить информацию о текущем пользователе
| true
a|
* *200* - возвращается информация о пользователе
* *401* - значит запрос не содержал токен
* *404* - значит пользователь не найден

|`GET /profile/{user-id}`
| Получить информацию о другом пользователе
| false
a|
* *200* - возвращается информация о пользователе
* *404* - значит пользователь не найден

|`POST /editUserInfo`
| Редактировать профиль пользователя
| true
a|
* *200* - возвращается обновленная информация о пользователе
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /editEmail`
| Редактировать почту пользователя
| true
a|
* *200* - возвращается обновленный токен пользователя
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен
* *409* - значит введенный email уже занят

|`POST /editPassword`
| Редактировать почту пользователя
| true
a|
* *200* - возвращается обновленная информация о пользователе
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /addDog`
| Добавить собаку пользователю
| true
a|
* *200* - собака добавлена
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /editDog?dogId=2`
| Редактировать питомца пользователя
| true
a|
* *200* - информация отредактирована
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен
* *404* - значит нет собаки с таким id
* *409* - значит это не собака текущего пользователя

|`POST /delete?userId={user-id}`
|Удалить пользователя из базы данных *(метод для Тимура для быстрого удаления юзера из бд)*
| false
a|
* *200* - пользователь удален
* *404* - значит нет пользователя с таким id

|===

== Примеры запросов

=== `GET /profile` - получить профиль текущего пользователя

Пример ответа в случае успеха:

    {
        "id": 5,
        "email": "ainaard1@mail.ru",
        "name": null,
        "surname": "test1",
        "dateOfBirth": "2018-04-15T00:00:00.000+0000",
        "city": "Ufa",
        "district": null,
        "photo_path": null,
        "dogs": [
            {
                "id": 4,
                "name": "test",
                "breed": "test",
                "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                "sex": "test",
                "size": "test",
                "photo_path": null,
                "information": "test"
            }
        ],
        "contacts": {
            "PHONE": "891782235",
            "INSTAGRAM": "@britny1999",
            "VK": "dogger.website",
            "TELEGRAM": "dogger"
        }
    }

=== `GET /profile/{user-id}` - получить профиль другого пользователя

Пример ответа в случае успеха: см. `GET /profile`

=== `POST /editUserInfo` - редактировать профиль

Для редактирования профиля отправляется *Json*:

    {
        "name": "Aina",
        "surname": "test1",
        "photo_path": "test_url",
        "city": "Ufa",
        "dateOfBirth": "2018-04-15",
        "district": "Sovetskii",
        "contacts": {
            "phone": "891782235",
            "instagram": "@britny1999",
            "vk": "dogger.website",
            "telegram": "@AinaLikesSuicide"
        }
    }

Пример ответа в случае успеха: см. `GET /profile`

=== `POST /editEmail` - редактировать почту

Для редактирования почты отправляется *Json*:

    {
        "email": "test@mail.ru"
    }

Пример ответа в случае успеха:

    {
        "value": "eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFAbWFpbC5ydSIsImlkIjo1fQ.2U9J40aYY62OQWQywkQ37BPpA5HF9koMkjMSxXMqwjU7mpbD9bPzRIqTanKTRhhwe9udlwGhOhJbikly5zXE6Q",
        "status": "VALID"
    }

=== `POST /editPassword` - редактировать пароль

Для редактирования пароля отправляется *Json*:

    {
        "password": "test1"
    }

Пример ответа в случае успеха: см. `GET /profile`

=== `POST /addDog` - добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней, для этого клиент посылает *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog. Little bit coward",
        "photo_path": "test_url"
    }

При успешном запросе в профиле пользователя появится собака.

=== `POST /editDog?dogId=2` - редактировать информацию о собаке

Пользователь может редактировать информацию, для этого клиент посылает *Json*:


    {
        "name": "Jack",
        "breed": "teryer",
        "dateOfBirth": "2020-06-30T17:00:00.000000",
        "information": "goody",
        "photo_path": "test_url",
        "sex": "male",
        "size": "small"
    }

Пример ответа в случае успеха:

    {
        "id": 6,
        "name": "Jack",
        "breed": "teryer",
        "dateOfBirth": "2020-06-30T17:00:00.000+0000",
        "sex": "male",
        "size": "small",
        "photo_path": "test_url",
        "information": "goody"
    }

