= Описание API по Dogger

== Методы

|===
|Метод | Назначение
|`POST /signUp`
|Создать пользователя

|`POST /login`
|Авторизовать зарегистрированного пользователя

|`GET /profile`
|Получить информацию о пользователе

|`POST /profile`
|Редактировать профиль пользователя или добавить питомца
|===

=== Регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "login": "user",
        "password": "user1",
        "name": "User user user"
    }

=== Авторизация

Для авторизации отправляется *Json*:

    {
        "login": "user",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен. Все последующие запросы должны включать в себя значение данного токена.

=== Профиль

Чтобы перейти на страницу профиля, в заголовках запроса надо добавить
*Authorization* со значением полученного токена.

Для редактирования профиля пользователя отправляется *Json*:

    {
        "login": "kama",
        "password": "kama",
        "fullName": "Kamila Nigmetzyanova",
        "dateOfBirth": "1999-03-09"
    }