= Описание API по прогулкам

Примечание: если запрос нуждается в авторизации, в заголовках запроса надо добавить *Authorization* со значением
полученного после авторизации токена.

|===
|Запрос | Назначение | isAuthenticated | Response

|`POST /addMeeting`
| Добавить новую прогулку
| true
a|
* *200* - возвращается информация о новой прогулке
* *400* - значит дата прогулки истекла или запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /editMeeting?meetingId={meeting-id}`
| Редактировать прогулку
| true
a|
* *200* - возвращается информация об измененной прогулке
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен
* *403* - значит user не имеет прав на редактирование этой прогулки
* *404* - значит нет прогулки с таким id

|`GET /meetings/future`
| Получить список всех прогулок
| false
a|
* *200* - возвращается массив всех будущих прогулок

|`GET /meetings/joined?userId={user-id}`
| Получить список всех прогулок, в которых участвует пользователь
| true
a|
* *200* - возвращается массив прогулок, в которых участвует пользователь
* *401* - значит запрос не содержал токен
* *404* - значит нет пользователя с таким id

|`GET /meetings/my`
| Получить список всех прогулок, созданных текущим пользователем
| true
a|
* *200* - возвращается массив прогулок, созданных пользователем
* *401* - значит запрос не содержал токен

|`GET /meetings/{meeting-id}`
| Получить полную информацию о прогулке
| false
a|
* *200* - возвращается информация о прогулке
* *404* - значит нет прогулки с таким id

|`POST /meetings/{meeting-id}/join`
| Присоединиться к прогулке
| true
a|
* *200* - возвращается информация о прогулке
* *400* - значит пользователь уже участвует в прогулке
* *401* - значит запрос не содержал токен
* *404* - значит нет прогулки с таким id

|`POST /meetings/{meeting-id}/unjoin`
| Отсоединиться от прогулки
| true
a|
* *200* - возвращается информация о прогулке
* *400* - значит пользователь не участвует в прогулке
* *401* - значит запрос не содержал токен
* *404* - значит нет прогулки с таким id

|===

== Примеры запросов

=== `POST /addMeeting` - добавить прогулку

Пользователь может добавить новую прогулку/встречу, для этого клиент посылает *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "longitude": "65.56348",
        "latitude": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный пользователь
(который автоматически попадает в список участников мероприятия).
В ответ придет детальная информация о новой добавленной прогулке.

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== `POST /editMeeting?meetingId={meeting-id}` - редактировать прогулку

Пользователь может редактировать свою прогулку/встречу, для этого клиент посылает *Json*
(неизмененные поля будут заполнены старыми данными):

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "longitude": "65.56348",
        "latitude": "63.14327"
    }

Если такой прогулки не существует или пользователь не является ее создателем, вернется ошибка *403 Forbidden*.
Если пользователь неавторизован, вернется ошибка *401 Unauthorized*.
При успешном запросе вернется информация об обновленной прогулке.

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== `GET /meetings/future` - получить список всех прогулок

Пример ответа в случае успеха:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "date": "2020-04-30T17:00:00.000+0000",
        "longitude": 65.56348,
        "latitude": 63.14327,
        "participants": [
          {
            "id": 2,
            "surname": "test test test",
            "photo_path": null
          }
        ]
      },
      {
        "id": 7,
        "name": "Khakima 49-54",
        "date": "2020-04-30T17:00:00.000+0000",
        "longitude": 65.56348,
        "latitude": 63.14327,
        "participants": [
          {
            "id": 2,
            "surname": "test test test",
            "photo_path": null
          }
        ]
      }
    ]

=== `GET /meetings/joined/?userId={user-id}` - получить список всех прогулок, в которых участвует пользователь

Пример ответа в случае успеха: см. `GET /meetings/future`

=== `GET /meetings/my` - получить список всех прогулок, созданных пользователем

Пример ответа в случае успеха: см. `GET /meetings/future`

=== `GET /meetings/{meeting-id}` - получить детальную информацию о прогулке

Пример ответа при успешном запросе:

    {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "longitude": 65.56348,
        "latitude": 63.14327,
        "creatorId": 3,
        "participants": [
            {
                "id": 1,
                "name": "test",
                "surname": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "city": "Ufa",
                "district": "Sovetskiy",
                "photo_path": "test_url",
                "dogs": [
                    {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    },
                    {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    }
                ],
                "contacts": {
                    "PHONE": "891782235",
                    "INSTAGRAM": "@britny1999",
                    "VK": "dogger.website",
                    "TELEGRAM": "dogger"
                }
            }
        ]
    }

=== `POST /meetings/{meeting-id}/join` - присоединиться к прогулке

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== `POST /meetings/{meeting-id}/unjoin` - отсоединиться от прогулки

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`