= Описание API по возможностям пользователя

Примечание: если запрос нуждается в авторизации, в заголовках запроса надо добавить *Authorization* со значением
полученного после авторизации токена.

|===
|Запрос | Назначение | isAuthenticated | Response

|`POST /signUp`
| Зарегистрировать пользователя
| false
a|
* *200* - пользователь зарегистрирован
* *409* - значит введенный email уже занят

|`POST /login`
|Авторизовать зарегистрированного пользователя
| false
a|
* *200* - возвращается токен
* *400* - значит введенные email или пароль неверны

|`GET /profile`
|Получить информацию о текущем пользователе
| true
a|
* *200* - возвращается информация о пользователе
* *401* - значит запрос не содержал токен
* *404* - значит пользователь не найден

|`GET /profile/{user-id}`
| Получить информацию о другом пользователе
| false
a|
* *200* - возвращается информация о пользователе
* *404* - значит пользователь не найден

|`POST /editProfile`
| Редактировать профиль пользователя
| true
a|
* *200* - возвращается обновленная информация о пользователе
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /addDog`
| Добавить собаку пользователю
| true
a|
* *200* - собака добавлена
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /editDogs`
| Редактировать питомцев пользователя
| true
a|
* *200* - информация отредактирована
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /recover`
|Отправить запрос на восстановление пароля пользователя
| false
a|
* *200* - письмо на воостановление пароля отправлено
* *400* - значит нет пользователя с таким email

|`POST /recover/{user-id}`
|Восстановить пароль пользователя *(запрос из письма на восстановление, пока не доделано)*
| false
a|
* *200* - пароль изменен
* *404* - значит нет пользователя с таким id

|`GET /activate/{activation-code}`
|Активировать аккаунт пользователя
| false
a|
* *200* - пользователь активирован
* *404* - значит нет пользователя с таким activation code

|`POST /delete?userId={user-id}`
|Удалить пользователя из базы данных *(метод для Тимура для быстрого удаления юзера из бд)*
| false
a|
* *200* - пользователь удален
* *404* - значит нет пользователя с таким id

|===

== Примеры запросов

=== `POST /signUp` - регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "email": "user@mail.ru",
        "password": "user1",
        "fullName": "User user user",
        "city": "Kazan"
    }

=== `POST /login` - авторизация

Для авторизации отправляется *Json*:

    {
        "email": "user@mail.ru",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен.
Пример ответа в случае успеха:

    {
        "value": "eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVr",
        "status": "VALID"
    }

=== `GET /profile` - получить профиль текущего пользователя

Пример ответа в случае успеха:

    {
        "dogs": [
            {
                "id": 4,
                "name": "test",
                "breed": "test",
                "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                "sex": "test",
                "size": "test",
                "photo_path": null,
                "information": "test"
            }
        ],
        "fullName": "test1",
        "dateOfBirth": "2018-04-15T00:00:00.000+0000",
        "meetings": [],
        "id": 5,
        "email": "ainaard1@mail.ru"
    }

=== `GET /profile/{user-id}` - получить профиль другого пользователя

Пример ответа в случае успеха: см. `GET /profile`

=== `POST /editProfile` - редактировать профиль

Для редактирования профиля пользователя отправляется *Json*:

    {
        "password": "test",
        "fullName": "test1",
        "email": "ainaard1@mail.ru",
        "city": "Ufa",
        "dateOfBirth": "2018-04-15",
        "phoneNumber": "891776874326"
    }

Пример ответа в случае успеха: см. `GET /profile`

=== `POST /addDog` - добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней, для этого клиент посылает *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog. Little bit coward"
    }

При успешном запросе в профиле пользователя появится собака.

=== `POST /editDogs` - редактировать информацию о собаке

Пользователь может редактировать информацию своих питомцев. Для этого нужно отправить *Json*:

    [
      {
        "id": 5,
        "name": "tesla",
        "breed": "jack rassel",
        "dateOfBirth": "",
        "information": "good girl"
      },
        {
        ...
        }
    ]


=== `POST /recover` - восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.
