= Описание API по Dogger

== Методы

|===
|Метод | Назначение
|`POST /signUp`
|Создать пользователя

|`POST /login`
|Авторизовать зарегистрированного пользователя

|`GET /profile`
|Получить информацию о пользователе

|`POST /profile`
|Редактировать профиль пользователя

|`POST /addDog`
|Добавить собаку пользователю

|`POST` /recover/{user-id}
|Восстановить пароль пользователя

|`GET` /activate/{activation-code}
|Активировать аккаунт пользователя

|`POST /addMeeting`
|Добавить новое мероприятие

|`GET /meetings`
|Получить список всех мероприятий

|`POST /meetings/{id}`
|Получить полную информацию о прогулке

|`POST` /delete
|Удалить пользователя из базы данных

|===

=== Регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "login": "user",
        "password": "user1",
        "fullName": "User user user"
    }

=== Авторизация

Для авторизации отправляется *Json*:

    {
        "login": "user",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен.

*Все последующие запросы должны включать в себя значение данного токена.*

=== Профиль

Чтобы перейти на страницу профиля, в заголовках запроса надо добавить *Authorization* со значением полученного токена.

Для редактирования профиля пользователя отправляется *Json*:

    {
        "login": "kama",
        "password": "kama",
        "fullName": "Kamila Nigmetzyanova",
        "dateOfBirth": "1999-03-09"
    }

=== Добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней.
Чтобы добавить питомца, следует отправить *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog.A little bit coward"
    }

При успешном запросе в профиле пользователя появится собака.

=== Восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "login": "test",
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.

=== Добавить мероприятие

Пользователь может добавить новое мероприятие/митинг/ивент.
Чтобы добавить мероприятие, следует отправить *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный
пользователь (который автоматически попадает в список участников мероприятия). В списке всех митингов появится новый.

=== Получить список всех мероприятий

Можно отобразить список всех прогулок в ответ на *GET /meetings*:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      },
      {
        "id": 7,
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 0
      }
    ]

=== Получить детальную информацию о прогулке

Ответ выглядит следующим образом:

    {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": {
            "id": 1,
            "login": "aina",
            "password": "$2a$10$EIcwg0/uD1qHxnb5yn/nVOcHRNkBcxHZ8qtKOyCmC9AW1wKsl0VY.",
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "dateOfBirth": null,
            "activationCode": "20b2977a-b1e8-4613-9bd9-069f44109c0c",
            "active": false,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
            "questions": [],
            "answers": [],
            "myMeetings": [
                {
                    "id": 3,
                    "name": "Khakima 47-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                },
                {
                    "id": 7,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                }
            ]
        },
        "participants": [
            {
                "id": 1,
                "login": "aina",
                "password": "$2a$10$EIcwg0/uD1qHxnb5yn/nVOcHRNkBcxHZ8qtKOyCmC9AW1wKsl0VY.",
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "activationCode": "20b2977a-b1e8-4613-9bd9-069f44109c0c",
                "active": false,
                "photo_path": null,
                "dogs": [
                    {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    },
                    {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    }
                ],
                "questions": [],
                "answers": [],
                "myMeetings": [
                    {
                    "id": 3,
                    "name": "Khakima 47-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                    },
                    {
                    "id": 7,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                    }
                ]
            },
            {
                "id": 2,
                "login": "kamila",
                "password": "$2a$10$tMOgLBRk87af5ubbKSPyQOUT00RZKOC8oAc4zOffWGmxZmo62oY6i",
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "activationCode": "02f6f7f5-126e-49c1-876f-c377c5a09a19",
                "active": false,
                "photo_path": null,
                "dogs": [],
                "questions": [],
                "answers": [],
                "myMeetings": []
            }
        ]
    }

=== Удалить пользователя

Можно удалить пользователя из базы данных, отправив запрос:

    {
        "login": "test"
    }
