= Описание API по прогулкам

|===
|Запрос | Назначение | isAuthenticated | Response

|`POST /addMeeting`
| Добавить новую прогулку
| true
a|
* *200* - возвращается информация о новой прогулке
* *400* - значит запрос построен неправильно
* *401* - значит запрос не содержал токен

|`POST /editMeeting?meetingId={meeting-id}`
| Редактировать прогулку
| true
a|
* *200* - возвращается информация об измененной прогулке
* *400* - значит запрос построен неправильно или нет прогулки с таким id
* *401* - значит запрос не содержал токен
* *403* - значит user не имеет прав на редактирование этой прогулки

|`GET /meetings/future`
| Получить список всех прогулок
| false
a|
* *200* - возвращается массив всех будущих прогулок

|`GET /meetings/joined?userId={user-id}`
| Получить список всех прогулок, в которых участвует пользователь
| true
a|
* *200* - возвращается массив прогулок, в которых участвует пользователь
* *400* - значит нет пользователя с таким id
* *401* - значит запрос не содержал токен

|`GET /meetings/my`
| Получить список всех прогулок, созданных текущим пользователем
| true
a|
* *200* - возвращается массив прогулок, созданных пользователем
* *401* - значит запрос не содержал токен

|`GET /meetings/{meeting-id}`
| Получить полную информацию о прогулке
| false
a|
* *200* - возвращается информация о прогулке
* *400* - значит нет прогулки с таким id

|`POST /meetings/{meeting-id}/join`
| Присоединиться к прогулке
| true
a|
* *200* - возвращается информация о прогулке
* *400* - значит нет прогулки с таким id или пользователь уже участвует в ней
* *401* - значит запрос не содержал токен

|`POST /meetings/{meeting-id}/unjoin`
| Отсоединиться от прогулки
| true
a|
* *200* - возвращается информация о прогулке
* *400* - значит нет прогулки с таким id или пользователь не участвует в ней
* *401* - значит запрос не содержал токен

|===

== Примеры запросов

=== `POST /addMeeting` - добавить прогулку

Пользователь может добавить новую прогулку/встречу, для этого клиент посылает *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный пользователь
(который автоматически попадает в список участников мероприятия).
В ответ придет детальная информация о новой добавленной прогулке.

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== `POST /editMeeting?meetingId={meeting-id}` - редактировать прогулку

Пользователь может редактировать свою прогулку/встречу, для этого клиент посылает *Json*
(неизмененные поля будут заполнены старыми данными):

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

Если такой прогулки не существует или пользователь не является ее создателем, вернется ошибка *403 Forbidden*.
Если пользователь неавторизован, вернется ошибка *401 Unauthorized*.
При успешном запросе вернется информация об обновленной прогулке.

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== `GET /meetings/future` - получить список всех прогулок

Пример ответа в случае успеха:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creatorId": 3,
        "creatorEmail": "test@mail.ru",
        "participants_count": 2
      },
      {
        "id": 7,
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creatorId": 3,
        "creatorEmail": "test@mail.ru",
        "participants_count": 0
      }
    ]

=== `GET /meetings/joined/?userId={user-id}` - получить список всех прогулок, в которых участвует пользователь

Пример ответа в случае успеха:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creatorId": 3,
        "creatorEmail": "test@mail.ru",
        "participants_count": 2
      }
    ]

=== `GET /meetings/my` - получить список всех прогулок, созданных пользователем

Пример ответа в случае успеха:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creatorId": 3,
        "creatorEmail": "test@mail.ru",
        "participants_count": 2
      }
    ]

=== `GET /meetings/{meeting-id}` - получить детальную информацию о прогулке

Пример ответа при успешном запросе:

    {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": {
            "id": 1,
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "password": null,
            "dateOfBirth": null,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
        },
        "participants": [
            {
                "id": 1,
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": [
                    {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    },
                    {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    }
                ],
            },
            {
                "id": 2,
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": []
            }
        ]
    }

=== Присоединиться к прогулке

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`

=== Отсоединиться от прогулки

Пример ответа в случае успеха: см. `GET /meetings/{meeting-id}`