= Описание API по Dogger

== Методы

=== Пользователь

|===
|Метод | Назначение
|`POST /signUp`
|Создать пользователя

|`POST /login`
|Авторизовать зарегистрированного пользователя

|`GET /profile`
|Получить информацию о текущем пользователе

|`GET /profile/{user-id}`
|Получить информацию о другом пользователе

|`POST /profile`
|Редактировать профиль пользователя

|`POST /addDog`
|Добавить собаку пользователю

|`POST` /recover/{user-id}
|Восстановить пароль пользователя

|`GET` /activate/{activation-code}
|Активировать аккаунт пользователя

|`POST` /delete
|Удалить пользователя из базы данных

|===

=== Прогулки

|===
|Метод | Назначение | isAuthenticated | Return type

|`POST /addMeeting`
| Добавить новую прогулку
| true
| массив всех будущих прогулок (мб пустой)

|`GET /meetings/all`
| Получить список всех прогулок
| false
| массив всех будущих прогулок (мб пустой)

|`GET /meetings/joined/{user-id}`
| Получить список всех прогулок, в которых участвует пользователь
| true
| массив прогулок, в которых участвует пользователь (мб пустой)

|`GET /meetings/my`
| Получить список всех прогулок, созданных текущим пользователем
| true
| массив прогулок, созданных пользователем (мб пустой)

|`GET /meetings/{meeting-id}`
| Получить полную информацию о прогулке
| false
| Детальная информация о прогулке или not found

|`POST /meetings/{meeting-id}/join`
| Присоединиться к прогулке
| true
| ok если присоединился, not found если уже участвуешь/нет такой прогулки,
401 если неавторизован

|`POST /meetings/{meeting-id}/unjoin`
| Отсоединиться от прогулки
| true
| ok если отсоединился, not found если не участвуешь/нет такой прогулки,
401 если неавторизован

|===

=== Регистрация

Для регистрации данные отправляются в формате *Json*:

    {
        "login": "user",
        "password": "user1",
        "fullName": "User user user",
        "city": "Kazan",
        "phoneNumber": "89176564663"
    }

=== Авторизация

Для авторизации отправляется *Json*:

    {
        "login": "user",
        "password": "user1"
    }

При успешной авторизации в ответе придет строка - токен.

*Все последующие запросы должны включать в себя значение данного токена.*

=== Профиль

Чтобы перейти на страницу профиля, в заголовках запроса надо добавить *Authorization* со значением полученного токена.

Для редактирования профиля пользователя отправляется *Json*:

    {
        "dogs": [
                  {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                  },
                  {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                  }
                ],
        "fullName": "test test test",
        "dateOfBirth": null,
        "meetings":
                [
                  {
                    "id": 3,
                    "name": "Khakima 47-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                  },
                  {
                    "id": 8,
                    "name": "Khakima 49-54",
                    "description": "For dog walkers from our district",
                    "date": "2020-04-30T17:00:00.000+0000",
                    "coordinateX": 65.56348,
                    "coordinateY": 63.14327
                  }
                ],
        "id": 1,
        "login": "aina"
    }

В ответе приходит *Json*:

    {
            "dogs": [
        {
          "id": 4,
          "name": "test",
          "breed": "test",
          "dateOfBirth": "2018-04-15T00:00:00.000+0000",
          "sex": "test",
          "size": "test",
          "photo_path": null,
          "information": "test"
        },
        {
          "id": 5,
          "name": "dog one",
          "breed": "labrador",
          "dateOfBirth": "2018-04-15T00:00:00.000+0000",
          "sex": "male",
          "size": "big",
          "photo_path": null,
          "information": "good"
        }
      ],
      "fullName": "Aina aina aina",
      "dateOfBirth": "1999-02-13T19:00:00.000+0000",
      "meetings": [],
      "login": "aina"
    }

Для получения страницы профиля другого пользователя токен отсылать не нужно. Ответ выглядит так:

    {
        "dogs": [],
        "fullName": "Test Test",
        "dateOfBirth": null,
        "meetings": [
            {
                "id": 18,
                "name": "Khakima 49-54",
                "description": "For dog walkers from our district",
                "date": "2020-04-30T17:00:00.000+0000",
                "coordinateX": 65.56348,
                "coordinateY": 63.14327
            }
        ],
        "id": 3,
        "login": "test"
    }

=== Добавить собаку

Пользователь может добавить в свой профиль собаку и информацию по ней.
Чтобы добавить питомца, следует отправить *Json*:

    {
        "name": "Mongol",
        "size": "small",
        "breed": "Zvegshnauzer",
        "dateOfBirth": "2018-04-15",
        "sex": "male",
        "information": "very energetic, friendly dog.A little bit coward"
    }

При успешном запросе в профиле пользователя появится собака.

=== Восстановить пароль

Чтобы восстановить забытый пароль, нужно отправить *Json*:

    {
        "login": "test",
        "email": "ainaard@mail.ru"
    }

При успешном запросе, на почту пользователя придет письмо с дальнейшими указаниями.

=== Удалить пользователя

Можно удалить пользователя из базы данных, отправив запрос:

    {
        "login": "test"
    }

=== Добавить прогулку

Пользователь может добавить новую прогулку/встречу.
Чтобы добавить мероприятие, следует отправить *Json*:

    {
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000000",
        "coordinateX": "65.56348",
        "coordinateY": "63.14327"
    }

При успешном запросе в базе данных появится мероприятие, автором которого будет текущий авторизованный пользователь
(который автоматически попадает в список участников мероприятия).
В списке всех митингов появится новый.

=== Получить список всех прогулок

Можно отобразить список всех прогулок в ответ на *GET /meetings/all*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      },
      {
        "id": 7,
        "name": "Khakima 49-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 0
      }
    ]

=== Получить список всех прогулок, в которых участвует пользователь

Можно отобразить список всех прогулок в ответ на *GET /meetings/joined/{user-id}*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      }
    ]

=== Получить список всех прогулок, созданных пользователем

Можно отобразить список всех прогулок в ответ на *GET /meetings/my*. Пример ответа:

    [
      {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": 1,
        "participants_count": 2
      }
    ]

=== Получить детальную информацию о прогулке

Ответ выглядит следующим образом:

    {
        "id": 3,
        "name": "Khakima 47-54",
        "description": "For dog walkers from our district",
        "date": "2020-04-30T17:00:00.000+0000",
        "coordinateX": 65.56348,
        "coordinateY": 63.14327,
        "creator": {
            "id": 1,
            "login": "aina",
            "fullName": "test test test",
            "email": "kamila.nigmet@gmail.com",
            "dateOfBirth": null,
            "photo_path": null,
            "dogs": [
                {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                },
                {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                }
            ],
        },
        "participants": [
            {
                "id": 1,
                "login": "aina",
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": [
                    {
                    "id": 1,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    },
                    {
                    "id": 2,
                    "name": "test",
                    "breed": "test",
                    "dateOfBirth": "2018-04-15T00:00:00.000+0000",
                    "sex": "test",
                    "size": "test",
                    "photo_path": null,
                    "information": "test"
                    }
                ],
            },
            {
                "id": 2,
                "login": "kamila",
                "fullName": "test test test",
                "email": "kamila.nigmet@gmail.com",
                "dateOfBirth": null,
                "photo_path": null,
                "dogs": []
            }
        ]
    }

=== Присоединиться к прогулке

После получения запроса проверяется, участвует ли пользователь в выбранной прогулке или еще нет, затем пользователь
добавляется в участники, если не был там.

=== Отсоединиться от прогулки

После получения запроса проверяется, участвует ли пользователь в выбранной прогулке или еще нет, затем пользователь
убирается из участников, если был там.


