POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "test",
  "password": "test",
  "fullName": "test",
  "email": "ainaard@mail.ru",
  "city": "Ufa",
  "phoneNumber": "891776874326"
}

###

POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina",
  "fullName": "test test test",
  "email": "kamila.nigmet@gmail.com"
}

###

GET http://localhost:8080/activate/386eb92a-b45c-4590-ad8f-5f661fc75137
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

<> 2020-03-31T080522.200.json
<> 2020-03-31T080024.200.json

###

GET http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###

POST http://localhost:8080/addDog
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3QiLCJpZCI6Mn0.m7Oz8HaszHKNBP4-lOsLeAeMASit66XWTIYUtqzu4ege-bU-9rbmZGqDGqNfDSrhMK9us_6SCUyQln_opyDSFw

{
  "name": "test",
  "size": "test",
  "breed": "test",
  "dateOfBirth": "2018-04-15",
  "sex": "test",
  "information": "test"
}

###

POST http://localhost:8080/delete
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "kama"
}

###

POST http://localhost:8080/addMeeting
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

{
  "name": "Khakima 49-54",
  "description": "For dog walkers from our district",
  "date": "2020-04-30T17:00:00.000000",
  "coordinateX": "65.56348",
  "coordinateY": "63.14327"
}

###

GET http://localhost:8080/meetings
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###

GET http://localhost:8080/meetings/12
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###

POST http://localhost:8080/meetings/10
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###