POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "password": "test",
  "fullName": "test",
  "email": "ainaard1@mail.ru",
  "city": "Ufa",
  "phoneNumber": "891776874326"
}

###

GET http://localhost:8080/activate/84882ee1-54d1-484d-8cf6-5eec4d986ca1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "email": "ainaard1@mail.ru",
  "password": "test"
}

<> 2020-03-31T080522.200.json
<> 2020-03-31T080024.200.json

###

GET http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmRAbWFpbC5ydSIsImlkIjoyMX0.HcoUpo4kGLtpDksqTOMBFp36zDqT0aexfRoJwJVJ5_7ItvTZDnhAnWPGby2z8j-QDwEHJYlcShqxprhIjyMBgw

###

GET http://localhost:8080/profile/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/addDog
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3QiLCJpZCI6Mn0.m7Oz8HaszHKNBP4-lOsLeAeMASit66XWTIYUtqzu4ege-bU-9rbmZGqDGqNfDSrhMK9us_6SCUyQln_opyDSFw

{
  "name": "test",
  "size": "test",
  "breed": "test",
  "dateOfBirth": "2018-04-15",
  "sex": "test",
  "information": "test"
}

###

POST http://localhost:8080/editDogs
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

[
  {
    "id": 3,
    "name": "",
    "breed": "jack",
    "dateOfBirth": "",
    "information": "goody"
  }
]

###
POST http://localhost:8080/delete/?userId=21
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

POST http://localhost:8080/addMeeting
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

{
  "name": "Khakima 49-54",
  "description": "For dog walkers from our district",
  "date": "2020-04-30T17:00:00.000000",
  "coordinateX": "65.56348",
  "coordinateY": "63.14327"
}

###

GET http://localhost:8080/meetings/all
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:8080/meetings/joined?userId=2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###

GET http://localhost:8080/meetings/my
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

###

GET http://localhost:8080/meetings/12
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/meetings/11/join
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImthbWlsYSIsImlkIjoyfQ.l89teY21A9FZ8yI9MRMzoABpxws6TS6kDes5X4xsNmZT4sGtnccwh-dnWcDsUqaif1D0x3XFMld5ooBRQ3rn0Q

###

POST http://localhost:8080/meetings/11/unjoin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImthbWlsYSIsImlkIjoyfQ.l89teY21A9FZ8yI9MRMzoABpxws6TS6kDes5X4xsNmZT4sGtnccwh-dnWcDsUqaif1D0x3XFMld5ooBRQ3rn0Q

###

GET http://localhost:8080/places/all
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/addPlace
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

{
  "name": "test place",
  "description": "coffee shop",
  "photoPath": "test_url",
  "placeType": "COFFEESHOP",
  "coordinateX": "55.73",
  "coordinateY": "55.76",
  "amenities": [ "WATER", "FOOD"]
}

###

GET http://localhost:8080/places/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###