POST http://localhost:8080/checkUserEmail
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "email": "test@mail.ru"
}

###

POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "email": "test3@mail.ru",
  "password": "test",
  "surname": "test",
  "name": "Aina"
}

###

GET http://localhost:8080/activate/84882ee1-54d1-484d-8cf6-5eec4d986ca1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "email": "aina@mail.ru",
  "password": "test"
}

<> 2020-03-31T080522.200.json
<> 2020-03-31T080024.200.json

###

GET http://localhost:8080/profile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVrxRLzlCh7yxt9ABBvbdoYHU--PMR5cRtgGE28rzHveHn3MpA

###

GET http://localhost:8080/profile/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/editUserInfo
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVrxRLzlCh7yxt9ABBvbdoYHU--PMR5cRtgGE28rzHveHn3MpA

{
  "name": "Aina",
  "surname": "Ard",
  "dateOfBirth": "1999-04-15",
  "city": "Kazan",
  "district": "Sovetskii",
  "contacts": {
    "phone": "891782235",
    "instagram": "@britny1999",
    "vk": "dogger.website",
    "telegram": "@AinaLikesSuicide"
  }
}

###

POST http://localhost:8080/editEmail
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVrxRLzlCh7yxt9ABBvbdoYHU--PMR5cRtgGE28rzHveHn3MpA

{
  "email": "aina@mail.ru"
}

###

POST http://localhost:8080/editPassword
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFAbWFpbC5ydSIsImlkIjo1fQ.2U9J40aYY62OQWQywkQ37BPpA5HF9koMkjMSxXMqwjU7mpbD9bPzRIqTanKTRhhwe9udlwGhOhJbikly5zXE6Q

{
  "password": "test"
}

###

POST http://localhost:8080/addDog
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFAbWFpbC5ydSIsImlkIjo1fQ.2U9J40aYY62OQWQywkQ37BPpA5HF9koMkjMSxXMqwjU7mpbD9bPzRIqTanKTRhhwe9udlwGhOhJbikly5zXE6Q

{
  "name": "test1",
  "size": "test1",
  "breed": "test1",
  "dateOfBirth": "2018-04-15",
  "sex": "male",
  "information": "test1"
}

###

POST http://localhost:8080/editDogs
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.uzVJT2sPv1oKWJSQBUsCyXoxKvv20www6dlDbr7ABQcPuAEbNVXCz5BZDRChdDjPopwqvtAwMx4VpeM_lwPMWQ

[
  {
    "id": 3,
    "name": "",
    "breed": "jack",
    "dateOfBirth": "",
    "information": "goody"
  }
]

###

POST http://localhost:8080/editProfile
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmQxQG1haWwucnUiLCJpZCI6NX0._pyZ-Cz7yyvzUXF6J54l6jG3zT5b15tNd3ShcVrxRLzlCh7yxt9ABBvbdoYHU--PMR5cRtgGE28rzHveHn3MpA

{
  "password": "test",
  "surname": "test1",
  "email": "ainaard1@mail.ru",
  "city": "Ufa",
  "dateOfBirth": "2018-04-15",
  "phoneNumber": "891776874326"
}

###
POST http://localhost:8080/delete/?userId=21
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

POST http://localhost:8080/addMeeting
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3RAbWFpbC5ydSIsImlkIjozfQ.rz1o5nRW0TCLQNyjHcy593O8gi2OMZDOfTpx_SCHnCDcgeptH3StTDzc0tMy5ZpHxnbM53jq7nGROo_fIWppqA

{
  "name": "Khakima 49-54",
  "description": "For dog walkers from our district",
  "date": "2020-06-30T17:00:00.000000",
  "longitude": "65.56348",
  "latitude": "63.14327"
}

###

POST http://localhost:8080/editMeeting?meetingId=27
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3RAbWFpbC5ydSIsImlkIjozfQ.rz1o5nRW0TCLQNyjHcy593O8gi2OMZDOfTpx_SCHnCDcgeptH3StTDzc0tMy5ZpHxnbM53jq7nGROo_fIWppqA

{
  "name": "new name",
  "description": "new description",
  "date": "2020-04-30T17:00:00.000000",
  "longitude": "65.56348",
  "latitude": "63.14327"
}

###

GET http://localhost:8080/meetings/future
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:8080/meetings/joined?userId=3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3RAbWFpbC5ydSIsImlkIjozfQ.rz1o5nRW0TCLQNyjHcy593O8gi2OMZDOfTpx_SCHnCDcgeptH3StTDzc0tMy5ZpHxnbM53jq7nGROo_fIWppqA

###

GET http://localhost:8080/meetings/my
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmRAbWFpbC5ydSIsImlkIjo1fQ.Oh_4Z0VDgh_BJ4e0UVpwQTe7ufR6KHZFCbFLoezwNPcFfme93lWk4tPPvnWuvLqMzDJO3IHqc3mwwyx58-fTHw

###

GET http://localhost:8080/meetings/12
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/meetings/11/join
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmRAbWFpbC5ydSIsImlkIjo1fQ.Oh_4Z0VDgh_BJ4e0UVpwQTe7ufR6KHZFCbFLoezwNPcFfme93lWk4tPPvnWuvLqMzDJO3IHqc3mwwyx58-fTHw

###

POST http://localhost:8080/meetings/11/unjoin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmFhcmRAbWFpbC5ydSIsImlkIjo1fQ.Oh_4Z0VDgh_BJ4e0UVpwQTe7ufR6KHZFCbFLoezwNPcFfme93lWk4tPPvnWuvLqMzDJO3IHqc3mwwyx58-fTHw

###

GET http://localhost:8080/places/all
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/addPlace
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3RAbWFpbC5ydSIsImlkIjozfQ.rz1o5nRW0TCLQNyjHcy593O8gi2OMZDOfTpx_SCHnCDcgeptH3StTDzc0tMy5ZpHxnbM53jq7nGROo_fIWppqA

{
  "name": "test place",
  "address": "Даурская 3",
  "photoPath": "test_url",
  "placeType": "COFFEESHOP",
  "longitude": "55.73",
  "latitude": "55.76",
  "amenities": [ "WATER", "FOOD"],
  "contacts": {
    "instagram" : "kamilamie",
    "site": "dogger.website"
  },
  "timecard": {
    "monday": "09:00-19:00",
    "tuesday": "09:00-19:00",
    "wednesday": "09:00-19:00",
    "thursday": "09:00-19:00",
    "friday": "09:00-19:00",
    "saturday": "09:00-14:00",
    "sunday": "09:00-14:00",
    "launch": "12:00-13:00"
  }
}

###

GET http://localhost:8080/places/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/places/1/addComment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6InRlc3RAbWFpbC5ydSIsImlkIjozfQ.rz1o5nRW0TCLQNyjHcy593O8gi2OMZDOfTpx_SCHnCDcgeptH3StTDzc0tMy5ZpHxnbM53jq7nGROo_fIWppqA

{
  "text": "beautiful place",
  "rating": "5"
}

###

GET http://localhost:8080/amenities
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
